"""added username field in the user model

Revision ID: 1079b19afaeb
Revises: abf092c36746
Create Date: 2026-07-04 17:11:02.335192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1079b19afaeb'
down_revision: Union[str, Sequence[str], None] = 'abf092c36746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('usernane', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['usernane'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'usernane')
    # ### end Alembic commands ###
