"""added default time on updated_at field

Revision ID: 4ae3a8e2af7e
Revises: cf78ebec1a65
Create Date: 2026-07-04 19:41:42.040906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ae3a8e2af7e'
down_revision: Union[str, Sequence[str], None] = 'cf78ebec1a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
