"""added more fields in the school model

Revision ID: bfff1b435af0
Revises: 1079b19afaeb
Create Date: 2026-07-04 18:12:08.708800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfff1b435af0'
down_revision: Union[str, Sequence[str], None] = '1079b19afaeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('phone', sa.String(), nullable=False))
    op.add_column('schools', sa.Column('school_email', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('address', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('ownership', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('mission', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('vission', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('school_logo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'school_logo')
    op.drop_column('schools', 'vission')
    op.drop_column('schools', 'mission')
    op.drop_column('schools', 'ownership')
    op.drop_column('schools', 'address')
    op.drop_column('schools', 'school_email')
    op.drop_column('schools', 'phone')
    # ### end Alembic commands ###
