"""updated all models to use base model and tenant base model

Revision ID: cf78ebec1a65
Revises: bfff1b435af0
Create Date: 2026-07-04 19:27:13.310672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf78ebec1a65'
down_revision: Union[str, Sequence[str], None] = 'bfff1b435af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permissions_school_id'), table_name='permissions')
    op.drop_column('permissions', 'school_id')
    op.drop_index(op.f('ix_role_permissions_school_id'), table_name='role_permissions')
    op.drop_column('role_permissions', 'school_id')
    op.drop_constraint(op.f('roles_school_id_fkey'), 'roles', type_='foreignkey')
    op.drop_index(op.f('ix_schools_school_id'), table_name='schools')
    op.drop_column('schools', 'school_id')
    op.drop_index(op.f('ix_user_roles_school_id'), table_name='user_roles')
    op.drop_column('user_roles', 'school_id')
    op.drop_constraint(op.f('users_school_id_fkey'), 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('users_school_id_fkey'), 'users', 'schools', ['school_id'], ['id'])
    op.add_column('user_roles', sa.Column('school_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_user_roles_school_id'), 'user_roles', ['school_id'], unique=False)
    op.add_column('schools', sa.Column('school_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_schools_school_id'), 'schools', ['school_id'], unique=False)
    op.create_foreign_key(op.f('roles_school_id_fkey'), 'roles', 'schools', ['school_id'], ['id'])
    op.add_column('role_permissions', sa.Column('school_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_role_permissions_school_id'), 'role_permissions', ['school_id'], unique=False)
    op.add_column('permissions', sa.Column('school_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_permissions_school_id'), 'permissions', ['school_id'], unique=False)
    # ### end Alembic commands ###
